config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
     resources :comments
  end
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title , presence: true, length: {minimum: 5}
  validates :text , presence: true, length: {minimum: 1}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :body, presence: true, length: {minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "user", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
    
  end

  def create
    @article = Article.new(article_params)
  
    if @article.save
      redirect_to @article
    else 
      render "new"    
    end

    #render plain: params[:article].inspect
  end


  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else 
      render "show"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  
  end


  private
    def article_params
      params.require(:article).permit(:title, :text)
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "user", password: "password", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end 


private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
 
<%= form_with(model: @article) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1> Update an Article </h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1> Index here </h1>

<p>
| <%= link_to "Create New Article" , new_article_path %> |
</p>


<table>
  <tr>
    <th> Title </th> <th> Text </th>
    <th colspan="2"></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td> <%= article.title %>  </td>
      <td> <%= article.text %>  </td>
      <td> | <%= link_to "Show" , article_path(article) %>  | </td>
      <td> <%= link_to "Edit" , edit_article_path(article) %> | </td>
      <td> <%= link_to "Delete" , article_path(article), 
              method: :delete, data: {confirm: "are you sure?" } %> </td>
    </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<h1> Create an article </h1>

<%= render "form"  %>

app/views/articles/show.html.erb
<h1> This is for show </h1>

<p>
  <strong> Title </strong>
  <%= @article.title %>
</p>

<p>
  <strong> Text </strong>
  <%= @article.text %>
</p>
<hr>

<h2> Comments </h2>
<%= render @article.comments %>


<h2> Add a comment </h2> 
<%= render 'comments/form' %>


<%= link_to "Create New" , new_article_path %> | <%= link_to "View Articles" , articles_path %> | 
<%= link_to "Edit Article", edit_article_path(@article) %> 

app/views/comments/_comment.html.erb
<% #@article.comments.each do |comment| %>
  <p>  
  Commenter: <%= comment.commenter %>  
  <br>
  Comment: <%= comment.body %> <br>
  <%= link_to "|delete comment|" , [comment.article, comment] ,
        method: :delete,
        data: {confirm: "Sure?" } %>
  </p>
<% #end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@article , @article.comments.build] , local: true) do |form|  %>
<p>
  <%= form.label :commenter %> <br>
  <%= form.text_field :commenter %> 
</p> <p>
  <%= form.label :body %> <br>
  <%= form.text_area :body %> 
</p>
  <%= form.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>
<p>
|  <%= link_to "Article List", articles_path %> |  <br>
</p><p>
| <%= link_to "Create New Article" , new_article_path %> |
</p>